name: CI

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: yarn
      
      - name: Build
        run: yarn release
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: master 
            FOLDER: out 
        
